* SPICE netlist generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os)

X0 i0 1 sky130_fd_sc_hd__clkinv_1
X1 i1 sel 2 sky130_fd_sc_hd__nand2_1
X2 3 sel 1 2 sky130_fd_sc_hd__o21ai_0
V0 4 i0 DC 0
V1 5 i1 DC 0
V2 6 sel DC 0
V3 y 3 DC 0

************************
* end of SPICE netlist *
************************

