/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "multiple_modules.v:10" *)
module multiple_modules(a, b, c, y);
  (* src = "multiple_modules.v:10" *)
  input a;
  (* src = "multiple_modules.v:10" *)
  input b;
  (* src = "multiple_modules.v:10" *)
  input c;
  (* src = "multiple_modules.v:11" *)
  wire net1;
  (* src = "multiple_modules.v:10" *)
  output y;
  (* src = "multiple_modules.v:12" *)
  sub_module1 u1 (
    .a(a),
    .b(b),
    .y(net1)
  );
  (* src = "multiple_modules.v:13" *)
  sub_module2 u2 (
    .a(net1),
    .b(c),
    .y(y)
  );
endmodule

(* src = "multiple_modules.v:5" *)
module sub_module1(a, b, y);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "multiple_modules.v:5" *)
  input a;
  (* src = "multiple_modules.v:5" *)
  input b;
  (* src = "multiple_modules.v:5" *)
  output y;
  sky130_fd_sc_hd__and2_2 _3_ (
    .A(_0_),
    .B(_1_),
    .X(_2_)
  );
  assign _0_ = b;
  assign _1_ = a;
  assign y = _2_;
endmodule

(* src = "multiple_modules.v:1" *)
module sub_module2(a, b, y);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  (* src = "multiple_modules.v:1" *)
  input a;
  (* src = "multiple_modules.v:1" *)
  input b;
  (* src = "multiple_modules.v:1" *)
  output y;
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(_0_),
    .Y(_3_)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(_1_),
    .Y(_4_)
  );
  sky130_fd_sc_hd__nand2_1 _7_ (
    .A(_3_),
    .B(_4_),
    .Y(_2_)
  );
  assign _0_ = b;
  assign _1_ = a;
  assign y = _2_;
endmodule
