/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module bad_latch(clk, reset, d, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input clk;
  input d;
  output q;
  input reset;
  sky130_fd_sc_hd__and2b_2 _10_ (
    .A_N(_03_),
    .B(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_03_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _12_ (
    .A(_06_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _13_ (
    .A(_08_),
    .B(_09_),
    .Y(_07_)
  );
  \$_DLATCH_P_  _14_ (
    .D(_00_),
    .E(_02_),
    .Q(q)
  );
  assign _03_ = reset;
  assign _04_ = d;
  assign _00_ = _05_;
  assign _06_ = clk;
  assign _02_ = _07_;
endmodule
