/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "dff_asyncres.v:2" *)
module dff_asyncres(clk, async_reset, d, q);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "dff_asyncres.v:2" *)
  input async_reset;
  (* src = "dff_asyncres.v:2" *)
  input clk;
  (* src = "dff_asyncres.v:2" *)
  input d;
  (* src = "dff_asyncres.v:2" *)
  output q;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_0_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .RESET_B(_2_)
  );
  assign _0_ = async_reset;
  assign _2_ = _1_;
endmodule
