/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module good_mux(i0, i1, sel, y);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  input i0;
  input i1;
  input sel;
  output y;
  INVX1 _6_ (
    .A(_0_),
    .Y(_2_)
  );
  NAND2X1 _7_ (
    .A(_1_),
    .B(_4_),
    .Y(_3_)
  );
  OAI21X1 _8_ (
    .A(_2_),
    .B(_4_),
    .C(_3_),
    .Y(_5_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _4_ = sel;
  assign y = _5_;
endmodule
